### PR TITLE
create blog post for extending your graphql service

### PR DESCRIPTION
**Pull request by egoodwinx**

### CODE REVIEW

**Comment by egoodwinx** [comment]
I can fix prettier on the file I missed but I'm not sure why the other things are failing I think its an auth issue?

**Comment by kamilkisiela** [comment]
Hi @egoodwinx :) Do you think we could link to https://the-guild.dev/graphql/hive/federation somewhere? We're building this page to explain what GraphQL federation is about, what components it includes, how you can do federation with Hive etc etc. So far it's very basic, but we will improve it over time.

**Review by kamilkisiela — APPROVED** [review]

**Comment by egoodwinx** [comment]
@kamilkisiela Ran prettier in the author page, changed to just federation, and added the link 👍

**Comment by kamilkisiela** [comment]
https://the-guild.dev/blog/extending-your-graphql-service <3

**Pull request merged**
